spring.application.name=origin-backend

spring.datasource.url=jdbc:postgres://localhost:5432/origis
spring.datasource.username=origis
spring.datasource.password=origis

spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
